apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.backend }}
