
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-secrets 
  namespace: monitoring 
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_USER
      remoteRef:
        key: app-secrets
        property: GRAFANA_ADMIN_USER
    - secretKey: GRAFANA_PASSWORD
      remoteRef:
        key: app-secrets
        property: GRAFANA_ADMIN_PASSWORD
