
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secrets  
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: ARGO_ADMIN_ENABLED
      remoteRef:
        key: app-secrets
        property: ARGO_ADMIN_ENABLED
    - secretKey: ARGO_ADMIN_PASSWORD
      remoteRef:
        key: app-secrets
        property: ARGO_ADMIN_PASSWORD
