
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-secrets  
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JENKINS_USER
      remoteRef:
        key: app-secrets
        property: JENKINS_ADMIN_USERNAME
    - secretKey: JENKINS_PASSWORD
      remoteRef:
        key: app-secrets
        property: JENKINS_ADMIN_PASSWORD
