apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:ahmeedusamaa/app-gitops.git
  sshPrivateKey: # put your private SSH key here
  insecure: "false"
  enableLFS: "false"