apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: #add your GitHub repository URL here
  sshPrivateKey: #add your private key here
  insecure: "false"
  enableLFS: "false"